### ISSUE TITLE
检测到include错误，已禁用波形曲线，怎么解决？ 

### ISSUE THREAD

**Issue by zhwxChaos** [github0null/keil-assistant#36]
工程在keil里编译通过，但是在VS里用插件打开会有波浪线
源文件在c_cpp_properties.json里的 includePath中，但还是报 无法打开源文件

keil-assistant.log
`[info] Log at : 2021/1/5|13:24:48|GMT+0800

[SyntaxError: Unexpected token / in JSON at position 1239
	at JSON.parse (<anonymous>)
	at F.updateCppProperties (c:\Users\XXXXX\.vscode\extensions\cl.keil-assistant-1.7.0\dist\extension.js:1:10911)
	at F.<anonymous> (c:\Users\XXXXX\.vscode\extensions\cl.keil-assistant-1.7.0\dist\extension.js:1:12641)
	at Generator.next (<anonymous>)
	at c:\Users\XXXXX\.vscode\extensions\cl.keil-assistant-1.7.0\dist\extension.js:1:4542
	at new Promise (<anonymous>)
	at r (c:\Users\XXXXX\.vscode\extensions\cl.keil-assistant-1.7.0\dist\extension.js:1:4287)
	at F.load (c:\Users\XXXXX\.vscode\extensions\cl.keil-assistant-1.7.0\dist\extension.js:1:11372)
	at w.<anonymous> (c:\Users\XXXXX\.vscode\extensions\cl.keil-assistant-1.7.0\dist\extension.js:1:8799)
	at Generator.next (<anonymous>)
	at a (c:\Users\XXXXX\.vscode\extensions\cl.keil-assistant-1.7.0\dist\extension.js:1:4344)
	at processTicksAndRejections (internal/process/task_queues.js:94:5)]
[info] Log at : 2021/1/5|13:25:00|GMT+0800

[info] Log at : 2021/1/5|13:25:27|GMT+0800
`

**Comment by github0null** [comment]
你给的信息太少了
不过头文件找不到这种问题，基本上就是因为包含路径不对，没有别的情况
这个日志中出现的错误是 JSON 中不能含有注释，**不要手动改 cpp_properties.json**

**Comment by zhwxChaos** [comment]
贴不了图，有QQ 或者 邮箱没？

**Comment by github0null** [comment]
把你的 uvprojx 文件发来
还有 cpp_properties.json 的内容




------------------&nbsp;原始邮件&nbsp;------------------
发件人: "zhwxChaos"<notifications@github.com&gt;; 
发送时间: 2021年1月6日(星期三) 下午2:29
收件人: "github0null/keil-assistant"<keil-assistant@noreply.github.com&gt;; 
抄送: "曹磊"<2584456014@qq.com&gt;; "Comment"<comment@noreply.github.com&gt;; 
主题: Re: [github0null/keil-assistant] 检测到include错误，已禁用波形曲线，怎么解决？  (#36)

**Comment by github0null** [comment]
没发现有啥问题，你可以这样重置一下
1. 删除 cpp_properties.json
2. ctrl+shift+p 打开命令面板，输入 C/C++: Res，选择 重置 intelliSense 数据库
3. 重启 vscode 工作区，插件会自动生成 cpp_properties.json

**Comment by zhwxChaos** [comment]
QQQ，按照上面1，2，3操作，好了

**Comment by 858876586** [comment]
> 你给的信息太少了
> 不过头文件找不到这种问题，基本上就是因为包含路径不对，没有别的情况
> 这个日志中出现的错误是 JSON 中不能含有注释，**不要手动改 cpp_properties.json**

不手动修改 cpp_properties.json，那该如何修改它呢？
我手动添加了几个包含的头文件路径，保存后，重新打开工程，发现对这个文件的改动都撤销了，感觉像是被重置成了默认参数。
我该如何增加几个头文件路径呢？

**Comment by 858876586** [comment]
> > 你给的信息太少了
> > 不过头文件找不到这种问题，基本上就是因为包含路径不对，没有别的情况
> > 这个日志中出现的错误是 JSON 中不能含有注释，**不要手动改 cpp_properties.json**
> 
> 不手动修改 cpp_properties.json，那该如何修改它呢？
> 我手动添加了几个包含的头文件路径，保存后，重新打开工程，发现对这个文件的改动都撤销了，感觉像是被重置成了默认参数。
> 我该如何增加几个头文件路径呢？

刚才从另一个问题里找到您的答案了，通过在IDE中手动增加头文件路径，问题解决了。看来您这个插件每次读取keil工程的配置来生成的这个文件是吧。
